apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-be
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp-be
  template:
    metadata:
      labels:
        app: demoapp-be
    spec:
      containers:
        - name: demoapp-be
          image: pkdemoappneacr01.azurecr.io/demoapp-be:latest
          ports:
            - containerPort: 3000
          env:
            # MySQL container:
            # - name: MYSQLHOST
            #   value: "test-mysql.database.svc.cluster.local"
            # - name: MYSQLUSER
            #   value: "root"
            # - name: MYSQLPASSWORD
            #   value: "testpass"
            # - name: MYSQLDATABASE
            #   value: "demoapp"
            # - name: MYSQLPORT
            #   value: "3306"

            - name: MYSQLHOST
              value: "pk-demoapp-ne-mysql01.mysql.database.azure.com"
            - name: MYSQLUSER
              value: "demoadm"
            - name: MYSQLPASSWORD
              value: "MySQL4dm!n"
            - name: MYSQLDATABASE
              value: "demoapp"
            - name: MYSQLPORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-be
  namespace: backend
spec:
  selector:
    app: demoapp-be
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-be-ingress
  namespace: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - 132-164-227-30.sslip.io
      secretName: demoapp-be-tls
  rules:
    - host: 132-164-227-30.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demoapp-be
                port:
                  number: 3000
